### ISSUE TITLE
分享链接失效

### ISSUE THREAD

**Issue by jianzhang96** [GuHuangAI/NPP#1]
链接取消了，可以重新分享一下吗？谢谢！
![image](https://user-images.githubusercontent.com/31060586/155844009-d94385e2-ce91-441c-ac0c-1236126c8c71.png)

**Comment by GuHuangAI** [comment]
I'm sorry that i have no time to maintain this repo.
If you are interest in this work, please concat with me by email: huangyuhang@shu.edu.cn.
