### ISSUE TITLE
how to calculate mAP for Pascal-Person-Part

### ISSUE THREAD

**Issue by jianzhang96** [GuHuangAI/NPP#2]
Thank you for your excellent work! Would you like to tell me how to calculate mAP for Pascal-Person-Part dataset? I just found the PCKh for LIP dataset.

**Comment by GuHuangAI** [comment]
We refer to the mAP used in object detection. Please click [here](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/master/lib/dataset/COCODataset.py). And we replace the iou with oks. The detailed steps can be refered to [](https://zhuanlan.zhihu.com/p/270619106)

**Comment by GuHuangAI** [comment]
We refer to the mAP used in object detection. Please click [here](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/master/lib/dataset/COCODataset.py). And we replace the iou with oks. The detailed steps can be refered to [here](https://zhuanlan.zhihu.com/p/270619106)

**Comment by jianzhang96** [comment]
> We refer to the mAP used in object detection. Please click [here](https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/master/lib/dataset/COCODataset.py). And we replace the iou with oks. The detailed steps can be refered to [here](https://zhuanlan.zhihu.com/p/270619106)

Would you like to share the code? (The data format of Pascal-Person-Part is .mat file and is not .json file, so it is hart to use the coco api. And coco api does not provide the evaluation for per-class results.)

**Comment by GuHuangAI** [comment]
Please give me your email.

**Comment by jianzhang96** [comment]
> Please give me your email.

zhangjian@stu.pku.edu.cn.   Thanks a lot!

**Comment by applezhouyp** [comment]
> > Please give me your email.
> 
> [zhangjian@stu.pku.edu.cn](mailto:zhangjian@stu.pku.edu.cn). Thanks a lot!

Do you know how to calculate how to calculate mAP for Pascal-Person-Part dataset now? I also suffer this problem.

**Comment by applezhouyp** [comment]
> Please give me your email.

Can you also share me the evaluation code for Pascal-Person-Part dataset?  
My email is : yanghong.zhou@connect.polyu.hk
Many thanks.

**Comment by GuHuangAI** [comment]
> > Please give me your email.
> 
> Can you also share me the evaluation code for Pascal-Person-Part dataset? My email is : [yanghong.zhou@connect.polyu.hk](mailto:yanghong.zhou@connect.polyu.hk) Many thanks.

I have pushed the mAP.py, please check it.

**Comment by GuHuangAI** [comment]
> > Please give me your email.
> 
> Can you also share me the evaluation code for Pascal-Person-Part dataset? My email is : [yanghong.zhou@connect.polyu.hk](mailto:yanghong.zhou@connect.polyu.hk) Many thanks.
Note that the code is not complement, please set different T to calculate the mAP. If u want to use the code, make sure the input shape is the same as the pose_pred.npy which contains your predicted results.
