### ISSUE TITLE
PASCAL-Person-Part 中生成单人的图像

### ISSUE THREAD

**Issue by willer94** [GuHuangAI/NPP#3]
您好，PASCAL-Person-Part 是一个多人的数据集，您在论文中提到使用了Mask RCN生成了单人的图像。请问您是采用哪一个mask rcnn的哪一个实现？可否将生成的bbox文件分享出来，方便公平对比。谢谢！

**Comment by GuHuangAI** [comment]
Please refer to [https://github.com/open-mmlab/mmdetection/tree/master/configs/cascade_rcnn](here)
